### ISSUE TITLE
Caching scraping results

### ISSUE THREAD

**Issue by pfigue** [deeplook/vbbvg#6]
Didn't check the code, but I guess the BVG site is scraped always to fetch the info. Maybe it would be handy to cache it in some cPickle thingy (e.g. ~/.vbbvg/cache.scraped) with some expiration date inside.

**Comment by deeplook** [comment]
If you check the code you can see that only the departure tables are scraped. Caching this makes no sense since it's real-time data. The list of all stop names and IDs is contained in `vbbvg_stops.csv`, so there's nothing to cache. ;-)
