### ISSUE TITLE
OS packages missing

### ISSUE THREAD

**Issue by pfigue** [deeplook/vbbvg#7]
I had to install:

```
sudo apt-get install lib32z1-dev
```

Before the `pip install` step to avoid an [“/usr/bin/ld: cannot find -lz” error](http://stackoverflow.com/questions/3373995/usr-bin-ld-cannot-find-lz).

Maybe as part of the README, a _System Requirements_ section with the packages: libxml2-dev, libxslt1-dev, lib32z1-dev.

**Comment by deeplook** [comment]
Done, but will have to test myself...
